baseurl             = "https://williamdussault.com"
builddrafts         = false
canonifyurls        = true
contentdir          = "content"
languageCode        = "en-US"
layoutdir           = "layouts"
publishdir          = "public"
theme               = "hello-friend"
author              = "William Dussault"
title               = "William Dussault"
pygmentsuseclasses  = true
pluralizelisttitles = false
googleAnalytics     = "UA-123-45"
paginate = 5
copyright = " "

[params.logo]
logoText = "william dussault"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects"
  [[menu.main]]
    identifier = "wiki"
    name = "Wiki"
    url = "https://www.notion.so/dalloriam/Knowledge-Base-899cea17b51b46a5921a1d176235cc78"
