baseURL = "https://williamdussault.com"
languageCode = "en"
DefaultContentLanguage = "en"
title = "William Dussault"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Google Analytics
googleAnalytics = "UA-83434360-1"

[params]
title = "Hi There!"
author = "William Dussault"
description = "I'm William."
profilePicture = "images/profile.jpg"
keywords = ""
favicon = "favicons/"
customCss = []
customJs = []
mainSections = ["post"]
images = ["images/site-feature-image.png"]
# Google Site Verification
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"

## Math settings
[params.math]
enable = true  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/william-dussault-0a451093/"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/dalloriam"

[[params.socialIcons]]
icon = "fa-envelope"
title = "e-mail"
url = "mailto:william@dussault.dev"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"
